/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-10-27 15:52:57
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7fbaf1d86a70
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-10-27 15:52:57,277: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 15:52:57,277: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 15:52:57,277: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 15:52:57,277: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 15:52:57,278: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 15:52:57,280: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 15:52:57,280: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 15:52:57,288: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 15:52:57,288: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-10-27 15:52:57,894: INFO/MainProcess] Connected to redis://redis:6379//
[2022-10-27 15:52:57,906: INFO/MainProcess] mingle: searching for neighbors
[2022-10-27 15:52:58,948: INFO/MainProcess] mingle: all alone
[2022-10-27 15:52:59,027: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-10-27 15:52:59,028: INFO/MainProcess] celery@worker_send_msg ready.
[2022-10-27 15:53:00,202: INFO/MainProcess] sync with celery@worker_default

worker: Warm shutdown (MainProcess)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-10-27 17:18:16
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f3bb1632a70
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-10-27 17:18:16,749: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 17:18:16,750: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 17:18:16,750: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 17:18:16,750: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 17:18:16,750: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 17:18:16,751: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 17:18:16,751: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 17:18:16,751: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-27 17:18:16,751: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-10-27 17:18:17,270: INFO/MainProcess] Connected to redis://redis:6379//
[2022-10-27 17:18:17,280: INFO/MainProcess] mingle: searching for neighbors
[2022-10-27 17:18:18,297: INFO/MainProcess] mingle: all alone
[2022-10-27 17:18:18,323: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-10-27 17:18:18,323: INFO/MainProcess] celery@worker_send_msg ready.
[2022-10-27 18:02:49,200: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-27 18:06:34,814: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-27 19:09:27,626: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-27 20:04:42,887: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-27 22:50:32,652: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-27 22:50:32,938: WARNING/MainProcess] Substantial drift from celery@worker_default may mean clocks are out of sync.  Current drift is 9936 seconds.  [orig: 2022-10-27 22:50:32.887018 recv: 2022-10-27 20:04:56.267651]
[2022-10-27 22:50:46,978: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-27 22:51:00,068: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-28 02:26:58,980: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-28 04:15:43,884: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-28 06:03:16,387: INFO/MainProcess] missed heartbeat from celery@worker_default

worker: Warm shutdown (MainProcess)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-10-28 10:24:24
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f869442aa40
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-10-28 10:24:24,978: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:24:24,979: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:24:24,979: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:24:24,980: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:24:24,980: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:24:24,980: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:24:24,980: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:24:24,980: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:24:24,981: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-10-28 10:24:27,633: INFO/MainProcess] Connected to redis://redis:6379//
[2022-10-28 10:24:27,649: INFO/MainProcess] mingle: searching for neighbors
[2022-10-28 10:24:28,708: INFO/MainProcess] mingle: all alone
[2022-10-28 10:24:28,876: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-10-28 10:24:28,877: INFO/MainProcess] celery@worker_send_msg ready.

worker: Warm shutdown (MainProcess)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-10-28 10:27:01
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7ff9b5abaa70
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-10-28 10:27:01,645: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:27:01,650: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:27:01,651: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:27:01,651: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:27:01,651: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:27:01,651: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:27:01,651: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:27:01,651: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 10:27:01,652: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-10-28 10:27:02,935: INFO/MainProcess] Connected to redis://redis:6379//
[2022-10-28 10:27:02,941: INFO/MainProcess] mingle: searching for neighbors
[2022-10-28 10:27:04,241: INFO/MainProcess] mingle: all alone
[2022-10-28 10:27:05,603: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-10-28 10:27:05,604: INFO/MainProcess] celery@worker_send_msg ready.

worker: Warm shutdown (MainProcess)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-10-28 11:09:17
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f4a11f2aa70
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-10-28 11:09:17,915: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 11:09:17,916: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 11:09:17,916: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 11:09:17,917: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 11:09:17,917: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 11:09:17,917: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 11:09:17,917: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 11:09:17,917: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-28 11:09:17,917: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-10-28 11:09:18,535: INFO/MainProcess] Connected to redis://redis:6379//
[2022-10-28 11:09:18,543: INFO/MainProcess] mingle: searching for neighbors
[2022-10-28 11:09:19,564: INFO/MainProcess] mingle: all alone
[2022-10-28 11:09:19,580: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-10-28 11:09:19,580: INFO/MainProcess] celery@worker_send_msg ready.
[2022-10-28 12:47:56,258: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-28 12:58:02,140: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-28 18:01:24,248: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-28 18:57:06,951: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-28 18:58:35,971: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-28 21:49:22,353: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-28 21:49:35,359: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-29 01:25:25,325: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-29 01:25:34,564: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-29 01:25:48,162: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-29 04:29:48,340: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-29 08:15:05,628: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-29 08:30:33,327: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-29 15:13:10,133: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-29 23:57:57,707: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-30 01:06:09,127: WARNING/MainProcess] Substantial drift from celery@worker_default may mean clocks are out of sync.  Current drift is 4032 seconds.  [orig: 2022-10-30 01:06:08.940042 recv: 2022-10-29 23:58:56.667521]
[2022-10-30 01:54:43,475: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-30 05:20:06,102: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 00:56:11,694: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 00:56:21,544: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 00:56:35,683: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 03:53:00,507: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 03:53:11,488: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 03:53:25,243: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 07:29:14,317: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 07:29:22,848: INFO/MainProcess] missed heartbeat from celery@worker_default
/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-10-31 14:08:02
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f1c87d4ea40
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-10-31 14:08:02,446: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 14:08:02,447: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 14:08:02,448: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 14:08:02,448: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 14:08:02,449: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 14:08:02,449: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 14:08:02,449: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 14:08:02,449: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 14:08:02,449: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-10-31 14:08:05,466: INFO/MainProcess] Connected to redis://redis:6379//
[2022-10-31 14:08:05,472: INFO/MainProcess] mingle: searching for neighbors
[2022-10-31 14:08:06,491: INFO/MainProcess] mingle: all alone
[2022-10-31 14:08:06,518: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-10-31 14:08:06,518: INFO/MainProcess] celery@worker_send_msg ready.
/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-10-31 20:37:32
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f044180ea40
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-10-31 20:37:32,596: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 20:37:32,601: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 20:37:32,603: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 20:37:32,605: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 20:37:32,606: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 20:37:32,606: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 20:37:32,606: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 20:37:32,607: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-10-31 20:37:32,608: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-10-31 20:37:33,215: INFO/MainProcess] Connected to redis://redis:6379//
[2022-10-31 20:37:33,223: INFO/MainProcess] mingle: searching for neighbors
[2022-10-31 20:37:34,249: INFO/MainProcess] mingle: all alone
[2022-10-31 20:37:34,263: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-10-31 20:37:34,263: INFO/MainProcess] celery@worker_send_msg ready.
[2022-10-31 22:30:06,117: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 22:30:15,277: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 22:31:02,497: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 22:31:12,027: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-10-31 22:31:25,527: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-01 02:06:38,076: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-01 02:06:47,700: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-01 08:58:55,734: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-01 09:00:08,860: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-01 09:18:27,819: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 906, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 916, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1500, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1482, in _execute
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1484, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2022-11-01 09:18:27,917: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2022-11-01 09:18:28,029: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)


worker: Warm shutdown (MainProcess)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-01 15:21:02
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f676c22ea70
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-01 15:21:02,392: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 15:21:02,393: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 15:21:02,393: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 15:21:02,393: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 15:21:02,393: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 15:21:02,393: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 15:21:02,393: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 15:21:02,394: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 15:21:02,394: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-01 15:21:03,191: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-01 15:21:03,197: INFO/MainProcess] mingle: searching for neighbors
[2022-11-01 15:21:04,213: INFO/MainProcess] mingle: all alone
[2022-11-01 15:21:04,226: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-01 15:21:04,226: INFO/MainProcess] celery@worker_send_msg ready.

worker: Warm shutdown (MainProcess)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-01 17:36:21
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f2090952a70
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-01 17:36:21,584: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 17:36:21,584: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 17:36:21,584: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 17:36:21,584: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 17:36:21,585: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 17:36:21,585: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 17:36:21,585: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 17:36:21,585: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-01 17:36:21,585: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-01 17:36:22,464: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-01 17:36:22,470: INFO/MainProcess] mingle: searching for neighbors
[2022-11-01 17:36:23,489: INFO/MainProcess] mingle: all alone
[2022-11-01 17:36:23,510: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-01 17:36:23,510: INFO/MainProcess] celery@worker_send_msg ready.
[2022-11-01 18:05:11,902: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-01 18:50:24,492: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-01 18:51:40,523: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-01 19:40:41,259: INFO/MainProcess] missed heartbeat from celery@worker_default

worker: Warm shutdown (MainProcess)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-02 10:13:48
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f7ad399ea70
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-02 10:13:48,578: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 10:13:48,579: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 10:13:48,579: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 10:13:48,579: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 10:13:48,579: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 10:13:48,579: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 10:13:48,580: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 10:13:48,580: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 10:13:48,580: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-02 10:13:49,344: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-02 10:13:49,351: INFO/MainProcess] mingle: searching for neighbors
[2022-11-02 10:13:50,366: INFO/MainProcess] mingle: all alone
[2022-11-02 10:13:50,382: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-02 10:13:50,383: INFO/MainProcess] celery@worker_send_msg ready.
[2022-11-02 13:35:45,419: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-02 13:45:52,202: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-02 18:50:25,853: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-02 20:04:53,459: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-02 20:20:10,549: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 906, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 916, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1500, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1482, in _execute
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1484, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2022-11-02 20:20:10,626: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2022-11-02 20:20:10,737: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)


worker: Warm shutdown (MainProcess)
/usr/local/lib/python3.10/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-02 20:21:00
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7fe473ebea40
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-02 20:21:00,173: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 20:21:00,173: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 20:21:00,176: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 20:21:00,176: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 20:21:00,176: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 20:21:00,176: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 20:21:00,177: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 20:21:00,177: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-02 20:21:00,177: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-02 20:21:01,088: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-02 20:21:01,098: INFO/MainProcess] mingle: searching for neighbors
[2022-11-02 20:21:02,080: INFO/MainProcess] mingle: all alone
[2022-11-02 20:21:02,104: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-02 20:21:02,104: INFO/MainProcess] celery@worker_send_msg ready.
[2022-11-03 18:42:52,177: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-04 00:05:51,881: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-04 00:06:19,073: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-04 09:17:09,583: WARNING/MainProcess] Substantial drift from celery@worker_default may mean clocks are out of sync.  Current drift is 33051 seconds.  [orig: 2022-11-04 09:17:09.565463 recv: 2022-11-04 00:06:18.883160]
[2022-11-04 20:01:43,954: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-04 20:12:08,381: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-04 22:00:08,133: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-05 10:11:50,331: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-05 10:13:13,938: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-05 11:14:01,669: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-05 13:57:47,143: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-05 15:58:14,721: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 906, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python3.10/site-packages/kombu/transport/redis.py", line 916, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1500, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1482, in _execute
    return conn.retry.call_with_retry(
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1484, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/usr/local/lib/python3.10/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.10/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2022-11-05 15:58:15,019: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2022-11-05 15:58:15,209: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 10:07:42
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7ff18e023750
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 10:07:42,614: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:07:42,615: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:07:42,615: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:07:42,615: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:07:42,615: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:07:42,615: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:07:42,615: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:07:42,615: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:07:42,615: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 10:07:42,964: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 10:07:42,972: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 10:07:43,991: INFO/MainProcess] mingle: all alone
[2022-11-07 10:07:44,015: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 10:07:44,015: INFO/MainProcess] celery@worker_send_msg ready.

worker: Warm shutdown (MainProcess)
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 10:13:44
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f7d0a7c35d0
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 10:13:44,962: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:13:44,962: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:13:44,962: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:13:44,963: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:13:44,963: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:13:44,963: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:13:44,963: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:13:44,963: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:13:44,963: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 10:13:45,851: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 10:13:45,857: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 10:13:46,869: INFO/MainProcess] mingle: all alone
[2022-11-07 10:13:46,885: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 10:13:46,885: INFO/MainProcess] celery@worker_send_msg ready.

worker: Warm shutdown (MainProcess)
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 10:16:36
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7ff018207590
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 10:16:36,535: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:16:36,535: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:16:36,536: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:16:36,537: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:16:36,537: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:16:36,537: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:16:36,538: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:16:36,538: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 10:16:36,539: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 10:16:37,099: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 10:16:37,103: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 10:16:38,113: INFO/MainProcess] mingle: all alone
[2022-11-07 10:16:38,130: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 10:16:38,130: INFO/MainProcess] celery@worker_send_msg ready.
[2022-11-07 18:04:48,916: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-07 20:44:18,043: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 906, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 916, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1500, in parse_response
    response = self._execute(conn, conn.read_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1482, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1484, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2022-11-07 20:44:18,448: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2022-11-07 20:44:18,602: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-11-07 20:44:20,592: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -2 connecting to redis:6379. Name or service not known..
Trying again in 4.00 seconds... (2/100)


worker: Warm shutdown (MainProcess)
elastic yw181126
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 20:45:21
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7fb3b746e050
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 20:45:21,499: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:45:21,500: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:45:21,500: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:45:21,500: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:45:21,500: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:45:21,500: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:45:21,500: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:45:21,500: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:45:21,500: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 20:45:33,397: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 20:45:33,433: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 20:45:34,553: INFO/MainProcess] mingle: sync with 1 nodes
[2022-11-07 20:45:34,554: INFO/MainProcess] mingle: sync complete
[2022-11-07 20:45:34,618: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 20:45:34,619: INFO/MainProcess] celery@worker_send_msg ready.
[2022-11-07 20:48:48,747: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 906, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 916, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1500, in parse_response
    response = self._execute(conn, conn.read_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1482, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1484, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2022-11-07 20:48:48,890: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2022-11-07 20:48:48,925: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)


worker: Warm shutdown (MainProcess)
elastic yw181126
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 20:49:45
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7fa48363b4d0
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 20:49:45,269: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:49:45,269: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:49:45,269: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:49:45,269: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:49:45,269: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:49:45,269: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:49:45,270: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:49:45,270: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 20:49:45,270: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 20:49:47,848: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 20:49:47,857: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 20:49:48,913: INFO/MainProcess] mingle: all alone
[2022-11-07 20:49:48,933: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 20:49:48,933: INFO/MainProcess] celery@worker_send_msg ready.

worker: Warm shutdown (MainProcess)
elastic yw181126
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 21:12:20
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f740b6a1950
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 21:12:20,759: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:12:20,760: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:12:20,760: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:12:20,761: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:12:20,761: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:12:20,762: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:12:20,762: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:12:20,762: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:12:20,763: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 21:12:21,156: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 21:12:21,167: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 21:12:22,186: INFO/MainProcess] mingle: all alone
[2022-11-07 21:12:22,206: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 21:12:22,206: INFO/MainProcess] celery@worker_send_msg ready.

worker: Warm shutdown (MainProcess)
elastic yw181126
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 21:31:56
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f8f4bb6e0d0
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 21:31:56,806: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:31:56,807: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:31:56,807: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:31:56,807: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:31:56,807: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:31:56,807: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:31:56,807: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:31:56,808: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:31:56,808: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 21:31:57,181: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 21:31:57,188: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 21:31:58,220: INFO/MainProcess] mingle: all alone
[2022-11-07 21:31:58,242: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 21:31:58,242: INFO/MainProcess] celery@worker_send_msg ready.

worker: Warm shutdown (MainProcess)
elastic yw181126
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 21:42:38
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7ff206bff490
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 21:42:38,833: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:42:38,837: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:42:38,840: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:42:38,840: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:42:38,841: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:42:38,844: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:42:38,846: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:42:38,847: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:42:38,847: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 21:42:39,561: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 21:42:39,571: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 21:42:40,598: INFO/MainProcess] mingle: all alone
[2022-11-07 21:42:40,615: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 21:42:40,615: INFO/MainProcess] celery@worker_send_msg ready.

worker: Warm shutdown (MainProcess)
elastic yw181126
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 688, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 268, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/article/tasks.py", line 29
    return 'es文章同步成功'
                                 ^
IndentationError: unindent does not match any outer indentation level
elastic yw181126
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 688, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 268, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/article/tasks.py", line 29
    return 'es文章同步成功'
                                 ^
IndentationError: unindent does not match any outer indentation level
elastic yw181126
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 688, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 268, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/article/tasks.py", line 29
    return 'es文章同步成功'
                                 ^
IndentationError: unindent does not match any outer indentation level
elastic yw181126
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 688, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 268, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/article/tasks.py", line 29
    return 'es文章同步成功'
                                 ^
IndentationError: unindent does not match any outer indentation level
elastic yw181126
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 688, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 268, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/article/tasks.py", line 29
    return 'es文章同步成功'
                                 ^
IndentationError: unindent does not match any outer indentation level
elastic yw181126
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 688, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 268, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/article/tasks.py", line 29
    return 'es文章同步成功'
                                 ^
IndentationError: unindent does not match any outer indentation level
elastic yw181126
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 688, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 268, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/article/tasks.py", line 29
    return 'es文章同步成功'
                                 ^
IndentationError: unindent does not match any outer indentation level
elastic yw181126
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 688, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 268, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/article/tasks.py", line 29
    return 'es文章同步成功'
                                 ^
IndentationError: unindent does not match any outer indentation level
elastic yw181126
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 688, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 268, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/article/tasks.py", line 29
    return 'es文章同步成功'
                                 ^
IndentationError: unindent does not match any outer indentation level
elastic yw181126
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
             ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/celery.py", line 213, in main
    return celery(auto_envvar_prefix="CELERY")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/bin/worker.py", line 343, in worker
    worker = app.Worker(
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/worker/worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 111, in init_worker
    self.import_default_modules()
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 105, in import_default_modules
    raise response
  File "/usr/local/lib/python3.11/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 160, in __call__
    return self.throw()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vine/promises.py", line 157, in __call__
    retval = fun(*final_args, **final_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 688, in _autodiscover_tasks
    return self._autodiscover_tasks_from_names(packages, related_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/base.py", line 693, in _autodiscover_tasks_from_names
    return self.loader.autodiscover_tasks(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 221, in autodiscover_tasks
    mod.__name__ for mod in autodiscover_tasks(packages or (),
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in autodiscover_tasks
    return [find_related_module(pkg, related_name) for pkg in packages]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 247, in <listcomp>
    return [find_related_module(pkg, related_name) for pkg in packages]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/loaders/base.py", line 268, in find_related_module
    return importlib.import_module(module_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/code/article/tasks.py", line 29
    return 'es文章同步成功'
                                 ^
IndentationError: unindent does not match any outer indentation level
elastic yw181126
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 21:49:57
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7fdf68a4b3d0
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 21:49:57,369: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:49:57,370: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:49:57,370: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:49:57,370: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:49:57,370: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:49:57,371: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:49:57,371: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:49:57,371: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 21:49:57,371: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 21:49:57,670: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 21:49:57,675: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 21:49:58,692: INFO/MainProcess] mingle: all alone
[2022-11-07 21:49:58,708: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 21:49:58,708: INFO/MainProcess] celery@worker_send_msg ready.
[2022-11-07 22:08:36,423: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 906, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 916, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1500, in parse_response
    response = self._execute(conn, conn.read_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1482, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1484, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2022-11-07 22:08:36,557: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2022-11-07 22:08:36,614: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-11-07 22:08:38,645: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -2 connecting to redis:6379. Name or service not known..
Trying again in 4.00 seconds... (2/100)


worker: Warm shutdown (MainProcess)
elastic yw181126
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 22:09:42
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f174d63b750
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 22:09:42,487: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:09:42,487: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:09:42,487: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:09:42,488: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:09:42,488: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:09:42,488: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:09:42,488: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:09:42,488: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:09:42,488: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 22:09:44,231: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 22:09:44,306: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 22:09:45,361: INFO/MainProcess] mingle: all alone
[2022-11-07 22:09:45,480: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 22:09:45,481: INFO/MainProcess] celery@worker_send_msg ready.
[2022-11-07 22:12:18,831: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 906, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 916, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1500, in parse_response
    response = self._execute(conn, conn.read_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1482, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1484, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2022-11-07 22:12:18,874: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2022-11-07 22:12:18,889: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[2022-11-07 22:12:20,909: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -2 connecting to redis:6379. Name or service not known..
Trying again in 4.00 seconds... (2/100)


worker: Warm shutdown (MainProcess)
elastic yw181126
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 22:12:45
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f9a57f93690
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 22:12:45,246: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:12:45,246: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:12:45,246: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:12:45,247: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:12:45,247: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:12:45,247: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:12:45,247: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:12:45,248: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:12:45,248: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 22:12:46,337: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 22:12:46,351: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 22:12:47,400: INFO/MainProcess] mingle: all alone
[2022-11-07 22:12:47,611: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 22:12:47,612: INFO/MainProcess] celery@worker_send_msg ready.
elastic yw181126
/usr/local/lib/python3.11/site-packages/celery/platforms.py:840: SecurityWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  warnings.warn(SecurityWarning(ROOT_DISCOURAGED.format(
 
 -------------- celery@worker_send_msg v5.2.3 (dawn-chorus)
--- ***** ----- 
-- ******* ---- Linux-5.10.25-linuxkit-x86_64-with-glibc2.31 2022-11-07 22:14:32
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         boke:0x7f0f3c8b7750
- ** ---------- .> transport:   redis://redis:6379//
- ** ---------- .> results:     redis://redis:6379/
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> send_msg         exchange=send_msg(direct) key=send_msg
                

[tasks]
  . article.tasks.cogradient
  . users.tasks.send_sms_celery
  . users.tasks.timing

[2022-11-07 22:14:32,672: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:14:32,672: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:14:32,672: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_ROUTES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_routes instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:14:32,673: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_QUEUE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_queue instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:14:32,673: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_EXCHANGE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_exchange instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:14:32,673: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_DEFAULT_ROUTING_KEY' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_default_routing_key instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:14:32,673: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'BROKER_URL' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the broker_url instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:14:32,673: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_QUEUES' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_queues instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-11-07 22:14:32,673: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-11-07 22:14:33,118: INFO/MainProcess] Connected to redis://redis:6379//
[2022-11-07 22:14:33,127: INFO/MainProcess] mingle: searching for neighbors
[2022-11-07 22:14:34,150: INFO/MainProcess] mingle: all alone
[2022-11-07 22:14:34,168: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-11-07 22:14:34,168: INFO/MainProcess] celery@worker_send_msg ready.
[2022-11-07 23:03:44,190: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-08 01:40:05,106: WARNING/MainProcess] Substantial drift from celery@worker_default may mean clocks are out of sync.  Current drift is 9381 seconds.  [orig: 2022-11-08 01:40:05.092086 recv: 2022-11-07 23:03:44.064303]
[2022-11-08 01:40:19,151: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-08 01:40:31,285: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-08 02:35:14,126: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-08 02:36:03,503: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-08 02:36:25,228: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-08 05:22:11,011: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-08 05:22:23,592: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-08 08:43:22,506: INFO/MainProcess] missed heartbeat from celery@worker_default
[2022-11-08 09:21:51,574: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.11/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.11/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.11/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 1326, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 562, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 906, in _receive
    ret.append(self._receive_one(c))
               ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/transport/redis.py", line 916, in _receive_one
    response = c.parse_response()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1500, in parse_response
    response = self._execute(conn, conn.read_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1482, in _execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1484, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1471, in _disconnect_raise_connect
    raise error
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 1483, in <lambda>
    lambda: command(*args, **kwargs),
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 824, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 318, in read_response
    raw = self._buffer.readline()
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 249, in readline
    self._read_from_socket()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 195, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2022-11-08 09:21:51,849: WARNING/MainProcess] /usr/local/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2022-11-08 09:21:51,932: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error 111 connecting to redis:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)


worker: Warm shutdown (MainProcess)
